### ISSUE TITLE
cloudera archive jar files are not available 

### ISSUE THREAD

**Issue by SrinivasaDK** [fabiog1901/SingleNodeCDPCluster#27]
Hi All, 

Thanks for this repo and scripts. but now we are not able to build the CDP-DC as the below jar files are not available in mentioned archive location. Please advise.  

```
--2022-02-12 06:13:17--  https://archive.cloudera.com/CFM/csd/1.0.1.0/NIFI-1.9.0.1.0.1.0-12.jar
Resolving archive.cloudera.com (archive.cloudera.com)... 151.101.0.167, 151.101.64.167, 151.101.128.167, ...
Connecting to archive.cloudera.com (archive.cloudera.com)|151.101.0.167|:443... connected.
HTTP request sent, awaiting response... 302 /CFM/csd/1.0.1.0/NIFI-1.9.0.1.0.1.0-12.jar/
Location: /CFM/csd/1.0.1.0/NIFI-1.9.0.1.0.1.0-12.jar/ [following]
--2022-02-12 06:13:17--  https://archive.cloudera.com/CFM/csd/1.0.1.0/NIFI-1.9.0.1.0.1.0-12.jar/
Reusing existing connection to archive.cloudera.com:443.
HTTP request sent, awaiting response... 404 Not Found
2022-02-12 06:13:17 ERROR 404: Not Found.

--2022-02-12 06:13:18--  https://archive.cloudera.com/cdsw1/1.6.1/csd/CLOUDERA_DATA_SCIENCE_WORKBENCH-CDH6-1.6.1.jar
Resolving archive.cloudera.com (archive.cloudera.com)... 151.101.0.167, 151.101.64.167, 151.101.128.167, ...
Connecting to archive.cloudera.com (archive.cloudera.com)|151.101.0.167|:443... connected.
HTTP request sent, awaiting response... 302 /cdsw1/1.6.1/csd/CLOUDERA_DATA_SCIENCE_WORKBENCH-CDH6-1.6.1.jar/
Location: /cdsw1/1.6.1/csd/CLOUDERA_DATA_SCIENCE_WORKBENCH-CDH6-1.6.1.jar/ [following]
--2022-02-12 06:13:18--  https://archive.cloudera.com/cdsw1/1.6.1/csd/CLOUDERA_DATA_SCIENCE_WORKBENCH-CDH6-1.6.1.jar/
Reusing existing connection to archive.cloudera.com:443.
HTTP request sent, awaiting response... 404 Not Found
2022-02-12 06:13:18 ERROR 404: Not Found.

./setup.sh: line 159: cd: cdswjar/: No such file or directory
java.io.FileNotFoundException: CLOUDERA_DATA_SCIENCE_WORKBENCH-CDH6-1.6.1.jar (No such file or directory)


--2022-02-12 06:13:18--  https://archive.cloudera.com/CEM/centos7/1.x/updates/1.0.0.0/CEM-1.0.0.0-centos7-tars-tarball.tar.gz
Resolving archive.cloudera.com (archive.cloudera.com)... 151.101.0.167, 151.101.64.167, 151.101.128.167, ...
Connecting to archive.cloudera.com (archive.cloudera.com)|151.101.0.167|:443... connected.
HTTP request sent, awaiting response... 302 /CEM/centos7/1.x/updates/1.0.0.0/CEM-1.0.0.0-centos7-tars-tarball.tar.gz/
Location: /CEM/centos7/1.x/updates/1.0.0.0/CEM-1.0.0.0-centos7-tars-tarball.tar.gz/ [following]
--2022-02-12 06:13:19--  https://archive.cloudera.com/CEM/centos7/1.x/updates/1.0.0.0/CEM-1.0.0.0-centos7-tars-tarball.tar.gz/
Reusing existing connection to archive.cloudera.com:443.
HTTP request sent, awaiting response... 404 Not Found
2022-02-12 06:13:19 ERROR 404: Not Found.

```

**Comment by Chaffelson** [comment]
Hi @SrinivasaDK , I am not sure this repo is still maintained.
If you want to create a quick CDP cluster, then the tools in Cloudera-Labs are maintained by Cloudera and the community.
The [Edge2AI](https://github.com/cloudera-labs/edge2ai-workshop) tooling creates rapid single-node cluster, and [Cloudera-Deploy](https://github.com/cloudera-labs/cloudera-deploy) helps creates more complex deployments.

**Comment by fabiog1901** [comment]
Thanks @Chaffelson ! 

@abajwa-hw @DavidFowler  if this repo is no longer maintained, I should better archive it and update the README to the link Dan posted. Please let me know.

**Comment by DavidFowler** [comment]
@Chaffelson @fabiog1901 @abajwa-hw This repo is still actively used by Cloudera and partners.    The CDP Base part is maintained and what's being used for it's latest version.   The CDSW and NiFi parts have not been updated to latest versions after they were moved behind the required licensing (aka paywall).  There is a CDP Base 60 day trial license install available without a regular license which is what is being used.  This github does need to be refreshed so it allows someone to enter their license for CDSW/NiFi or remove those parts and just be CDP Base.  Probably it should be moved to Cloudera Labs.  I'll discuss with Ali.

**Comment by abajwa-hw** [comment]
@DavidFowler is correct. This script will just give a vanilla CDP-Base (formerly CDP-DC) sandbox using a 60day trial license without any addons like CDSW or NiFi. The Edge2AI github can be used those purposes

Thee errors you see can be treated as warnings...we'll plan to remove them

**Comment by fabiog1901** [comment]
Thanks Ali and Dave, will close this issue then.

**Comment by SrinivasaDK** [comment]
Thank you @fabiog1901 @Chaffelson @DavidFowler @abajwa-hw
