### ISSUE TITLE
is possible create this in a private centos7

### ISSUE THREAD

**Issue by johnfelipe** [fabiog1901/SingleNodeCDPCluster#28]
# localhost.localdomain.ibm.com:22 SSH-2.0-OpenSSH_7.4
	# localhost.localdomain.ibm.com:22 SSH-2.0-OpenSSH_7.4
	# localhost.localdomain.ibm.com:22 SSH-2.0-OpenSSH_7.4
	-- Start CM, it takes about 2 minutes to be ready
	Failed to start cloudera-scm-server.service: Unit not found.
	waiting 10s for CM to come up..
	waiting 10s for CM to come up..
	waiting 10s for CM to come up..
	waiting 10s for CM to come up..
	waiting 10s for CM to come up..
	waiting 10s for CM to come up..
	waiting 10s for CM to come up..
	waiting 10s for CM to come up..
	waiting 10s for CM to come up..
	waiting 10s for CM to come up..
	waiting 10s for CM to come up..
	waiting 10s for CM to come up..
	waiting 10s for CM to come up..
	waiting 10s for CM to come up..
	waiting 10s for CM to come up..
	waiting 10s for CM to come up..
	waiting 10s for CM to come up..
	waiting 10s for CM to come up..
	waiting 10s for CM to come up..
	waiting 10s for CM to come up..
	waiting 10s for CM to come up..
	waiting 10s for CM to come up..
	waiting 10s for CM to come up..
	waiting 10s for CM to come up..
	waiting 10s for CM to come up..
	waiting 10s for CM to come up..
	waiting 10s for CM to come up..
	waiting 10s for CM to come up..
	waiting 10s for CM to come up..
	waiting 10s for CM to come up..
	waiting 10s for CM to come up..
	waiting 10s for CM to come up..
	waiting 10s for CM to come up..
	waiting 10s for CM to come up..
	waiting 10s for CM to come up..
	waiting 10s for CM to come up..
	waiting 10s for CM to come up..
	waiting 10s for CM to come up..
	waiting 10s for CM to come up..
	waiting 10s for CM to come up..
	waiting 10s for CM to come up..
	waiting 10s for CM to come up..
	waiting 10s for CM to come up..
	waiting 10s for CM to come up..
	waiting 10s for CM to come up..
	waiting 10s for CM to come up..
	waiting 10s for CM to come up..
	waiting 10s for CM to come up..
	waiting 10s for CM to come up..
	waiting 10s for CM to come up..
	waiting 10s for CM to come up..
	waiting 10s for CM to come up..
	waiting 10s for CM to come up..
	waiting 10s for CM to come up..
	waiting 10s for CM to come up..
	waiting 10s for CM to come up..
	waiting 10s for CM to come up..
	waiting 10s for CM to come up..
	waiting 10s for CM to come up..
	waiting 10s for CM to come up..
	waiting 10s for CM to come up..
	waiting 10s for CM to come up..
	waiting 10s for CM to come up..
	waiting 10s for CM to come up..
	waiting 10s for CM to come up..
	waiting 10s for CM to come up..
	waiting 10s for CM to come up..
	waiting 10s for CM to come up..
	waiting 10s for CM to come up..
	waiting 10s for CM to come up..

how can solve this?

**Comment by johnfelipe** [comment]
https://gist.github.com/johnfelipe/dfee130f3754be231584529552432d47

this is more complete log from putty

**Comment by DavidFowler** [comment]
What env are you trying to use?  

setup.sh works for aws, azure, and gcp.  The gcp option to setup.sh is probably the closest to a generic vm type install but you may have to modify it for your particular env. (i.e. fix any needed missing rpm's on the CentOS install shown in the log preventing CM from installing correctly)

The setup_ibm.sh works for a CentOS 7 VM on IBM cloud and adds some ibm.com info in /etc/host needed for IBM Cloud when using /etc/hosts to resolve your hostname.

**Comment by johnfelipe** [comment]
where is sh file for Virtual Machine private with Esxi?

**Comment by johnfelipe** [comment]
./setup.sh gcp templates/base.json

installing to view
