### ISSUE TITLE
"./setup.sh aws templates/base.json" issues pls help for solve into centos 7 private

### ISSUE THREAD

**Issue by johnfelipe** [fabiog1901/SingleNodeCDPCluster#29]
https://gist.github.com/johnfelipe/3e27d019720ff304ff19713e906d86d1

pls help me for solve

**Comment by johnfelipe** [comment]
Anyone?

**Comment by johnfelipe** [comment]
@DavidFowler can u help me for install this into CENTOS 8
Pls
tnks

**Comment by DavidFowler** [comment]
The install scripts haven't been updated yet for CentOS 8.

**Comment by johnfelipe** [comment]
centos 6?
wich version pls

**Comment by asdaraujo** [comment]
@johnfelipe Take a look at these instructions here as an alternative: https://github.com/cloudera-labs/edge2ai-workshop/tree/trunk/setup#deploying-on-an-existing-vm

The repo above has been kept up to date with the latest versions.
